function fig = plot_lick_latency( ...
    T, cfg, mouseName, sessionDate)
% PLOT_LICK_LATENCY
% Plots reward-to-first-lick timing and lick latency across laps.
%
% Upper panel:
%   red dot   = reward delivery at time zero
%   white dot = first post-reward lick
%   gray line = reward-to-lick interval
%
% Lower panel:
%   individual first-lick latencies with a rolling median.

requiredVariables = { ...
    'Lap', ...
    'RewardCount', ...
    'LickLatency_s', ...
    'IsRewardedLap', ...
    'IsOmissionLap', ...
    'HasMultipleRewards', ...
    'HasFirstLick'};

for k = 1:numel(requiredVariables)
    if ~ismember(requiredVariables{k}, T.Properties.VariableNames)
        error('Latency table is missing variable %s.', ...
            requiredVariables{k});
    end
end

if isempty(T)
    error('Latency table is empty.');
end

if ~isfield(cfg, 'maxLickLatency_s') || ...
        ~isscalar(cfg.maxLickLatency_s) || ...
        ~isfinite(cfg.maxLickLatency_s) || ...
        cfg.maxLickLatency_s <= 0
    error('A finite positive cfg.maxLickLatency_s is required for plotting.');
end

if ~isfield(cfg, 'latencyRollingWindow_laps')
    cfg.latencyRollingWindow_laps = 10;
end

rollingWindow = max(1, round(cfg.latencyRollingWindow_laps));

if nargin < 3 || isempty(mouseName)
    mouseName = 'UnknownMouse';
end

if nargin < 4 || isempty(sessionDate)
    sessionDate = 'UnknownDate';
end

validReward = T.IsRewardedLap;
validLick = T.HasFirstLick;

fig = figure( ...
    'Color', 'w', ...
    'Name', sprintf('%s %s lick latency', mouseName, sessionDate), ...
    'Units', 'normalized', ...
    'Position', [0.18 0.08 0.64 0.82]);

tl = tiledlayout(fig, 2, 1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

%% Reward-to-first-lick raster
axRaster = nexttile(tl);
hold(axRaster, 'on');
set(axRaster, ...
    'Color', [0 0 0], ...
    'YDir', 'reverse', ...
    'Layer', 'top');

lickRows = find(validLick);
for k = 1:numel(lickRows)
    row = lickRows(k);
    plot(axRaster, ...
        [0 T.LickLatency_s(row)], ...
        [T.Lap(row) T.Lap(row)], ...
        '-', ...
        'Color', [0.55 0.55 0.55], ...
        'LineWidth', 0.7);
end

scatter(axRaster, ...
    zeros(sum(validReward), 1), ...
    T.Lap(validReward), ...
    28, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [1 0 0]);

scatter(axRaster, ...
    T.LickLatency_s(validLick), ...
    T.Lap(validLick), ...
    20, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [1 1 1], ...
    'MarkerEdgeColor', [1 1 1]);

xline(axRaster, 0, ':', ...
    'Color', [1 0.25 0.25], ...
    'LineWidth', 1);

xPadding = 0.03 * cfg.maxLickLatency_s;
xlim(axRaster, [-xPadding cfg.maxLickLatency_s]);
ylim(axRaster, [min(T.Lap) - 0.5 max(T.Lap) + 0.5]);

xlabel(axRaster, 'Time from reward delivery (s)');
ylabel(axRaster, 'Lap');
title(axRaster, sprintf( ...
    '%s  %s: reward to first lick', ...
    mouseName, ...
    sessionDate), ...
    'Interpreter', 'none');

hReward = scatter(axRaster, nan, nan, 28, ...
    'o', 'filled', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [1 0 0]);
hLick = scatter(axRaster, nan, nan, 20, ...
    'o', 'filled', ...
    'MarkerFaceColor', [1 1 1], ...
    'MarkerEdgeColor', [1 1 1]);

legend(axRaster, ...
    [hReward hLick], ...
    {'Reward delivery', 'First lick'}, ...
    'Location', 'southeast', ...
    'Color', [0.12 0.12 0.12], ...
    'TextColor', [1 1 1], ...
    'EdgeColor', [0.6 0.6 0.6]);

box(axRaster, 'on');

%% Lick latency across laps
axTrend = nexttile(tl);
hold(axTrend, 'on');

scatter(axTrend, ...
    T.Lap(validLick), ...
    T.LickLatency_s(validLick), ...
    28, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [0.25 0.25 0.25], ...
    'MarkerEdgeColor', [0.25 0.25 0.25]);

rollingLatency = movmedian( ...
    T.LickLatency_s, ...
    rollingWindow, ...
    'omitnan');

plot(axTrend, ...
    T.Lap, ...
    rollingLatency, ...
    '-', ...
    'Color', [0.85 0.10 0.10], ...
    'LineWidth', 2);

xlim(axTrend, [min(T.Lap) - 0.5 max(T.Lap) + 0.5]);
ylim(axTrend, [0 cfg.maxLickLatency_s]);

xlabel(axTrend, 'Lap');
ylabel(axTrend, 'First-lick latency (s)');
title(axTrend, sprintf( ...
    '%d-lap rolling median; %d omissions; %d rewarded laps without a lick', ...
    rollingWindow, ...
    sum(T.IsOmissionLap), ...
    sum(T.IsRewardedLap & ~T.HasFirstLick)));

grid(axTrend, 'on');
box(axTrend, 'on');

hIndividual = scatter(axTrend, nan, nan, 28, ...
    'o', 'filled', ...
    'MarkerFaceColor', [0.25 0.25 0.25], ...
    'MarkerEdgeColor', [0.25 0.25 0.25]);
hRolling = plot(axTrend, nan, nan, '-', ...
    'Color', [0.85 0.10 0.10], ...
    'LineWidth', 2);

legend(axTrend, ...
    [hIndividual hRolling], ...
    {'Individual lap', 'Rolling median'}, ...
    'Location', 'northeast');

end

