function fig = plot_lick_latency( ...
    latencyInput, cfg, mouseName, sessionDate)
% PLOT_LICK_LATENCY
% Compares reward-to-first-lick timing across one or more sessions.
%
% Each mouse receives a two-row block:
%   upper row  = one chronological raster per selected date
%   lower row  = one shared rolling-median comparison axis for that mouse
%
% Raster markers:
%   red dot   = reward delivery at time zero
%   white dot = first post-reward lick
%   gray line = reward-to-lick interval

latencyTables = normalize_latency_tables(latencyInput);
nSessions = numel(latencyTables);

mouseNames = normalize_session_labels( ...
    mouseName, ...
    nSessions, ...
    'UnknownMouse');

sessionDates = normalize_session_labels( ...
    sessionDate, ...
    nSessions, ...
    'UnknownDate');

requiredVariables = { ...
    'Lap', ...
    'RewardCount', ...
    'LickLatency_s', ...
    'IsRewardedLap', ...
    'IsOmissionLap', ...
    'HasMultipleRewards', ...
    'HasFirstLick'};

maxLap = 0;
for s = 1:nSessions
    T = latencyTables{s};

    for k = 1:numel(requiredVariables)
        if ~ismember(requiredVariables{k}, T.Properties.VariableNames)
            error( ...
                'Session %d latency table is missing variable %s.', ...
                s, ...
                requiredVariables{k});
        end
    end

    if isempty(T)
        error('Session %d latency table is empty.', s);
    end

    maxLap = max(maxLap, max(T.Lap));
end

if ~isfield(cfg, 'maxLickLatency_s') || ...
        ~isscalar(cfg.maxLickLatency_s) || ...
        ~isfinite(cfg.maxLickLatency_s) || ...
        cfg.maxLickLatency_s <= 0
    error('A finite positive cfg.maxLickLatency_s is required for plotting.');
end

if ~isfield(cfg, 'latencyRollingWindow_laps')
    cfg.latencyRollingWindow_laps = 10;
end

rollingWindow = max(1, round(cfg.latencyRollingWindow_laps));
displayMax_s = calculate_shared_display_max(latencyTables, cfg);

rollingLatencyBySession = cell(nSessions, 1);
for s = 1:nSessions
    rollingLatencyBySession{s} = movmedian( ...
        latencyTables{s}.LickLatency_s, ...
        rollingWindow, ...
        'omitnan');
end

trendDisplayMax_s = calculate_trend_display_max( ...
    rollingLatencyBySession, ...
    cfg);

mouseOrder = sort(unique(mouseNames));
dateOrder = sort(unique(sessionDates));

nMice = numel(mouseOrder);
nDates = numel(dateOrder);
dateColors = lines(nDates);

validate_mouse_date_pairs( ...
    mouseNames, ...
    sessionDates, ...
    mouseOrder, ...
    dateOrder);

figWidth = min(0.98, max(0.68, 0.25 * nDates));
figHeight = min(0.96, max(0.78, 0.43 * nMice));

fig = figure( ...
    'Color', 'w', ...
    'Name', 'Stacked lick latency by mouse', ...
    'Units', 'normalized', ...
    'Position', [ ...
        (1 - figWidth) / 2, ...
        (1 - figHeight) / 2, ...
        figWidth, ...
        figHeight]);

tl = tiledlayout(fig, 2 * nMice, nDates, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for m = 1:nMice
    mouseLabel = mouseOrder{m};
    rasterRow = 2 * m - 1;
    trendRow = 2 * m;

    mouseSessionIdx = find(strcmp(mouseNames, mouseLabel));
    availableDateColumns = find(arrayfun(@(d) any( ...
        strcmp(mouseNames, mouseLabel) & ...
        strcmp(sessionDates, dateOrder{d})), ...
        1:nDates));
    firstAvailableDateColumn = availableDateColumns(1);
    lastAvailableDateColumn = availableDateColumns(end);

    %% Raster row for this mouse
    for d = 1:nDates
        rasterTile = (rasterRow - 1) * nDates + d;
        axRaster = nexttile(tl, rasterTile);

        sessionIdx = find( ...
            strcmp(mouseNames, mouseLabel) & ...
            strcmp(sessionDates, dateOrder{d}));

        if isempty(sessionIdx)
            axis(axRaster, 'off');
            continue
        end

        plot_session_raster( ...
            axRaster, ...
            latencyTables{sessionIdx}, ...
            mouseNames{sessionIdx}, ...
            sessionDates{sessionIdx}, ...
            dateColors(d, :), ...
            displayMax_s, ...
            maxLap, ...
            d == firstAvailableDateColumn, ...
            m == 1 && d == lastAvailableDateColumn);
    end

    %% Rolling-median comparison row for this mouse
    trendTile = (trendRow - 1) * nDates + 1;
    axTrend = nexttile(tl, trendTile, [1 nDates]);
    hold(axTrend, 'on');

    curveHandles = gobjects(numel(mouseSessionIdx), 1);
    curveLabels = cell(numel(mouseSessionIdx), 1);

    curveCount = 0;
    for d = 1:nDates
        sessionIdx = find( ...
            strcmp(mouseNames, mouseLabel) & ...
            strcmp(sessionDates, dateOrder{d}));

        if isempty(sessionIdx)
            continue
        end

        curveCount = curveCount + 1;
        T = latencyTables{sessionIdx};

        curveHandles(curveCount) = plot(axTrend, ...
            T.Lap, ...
            rollingLatencyBySession{sessionIdx}, ...
            '-', ...
            'Color', dateColors(d, :), ...
            'LineWidth', 2);

        curveLabels{curveCount} = dateOrder{d};
    end

    xlim(axTrend, [0.5 maxLap + 0.5]);
    ylim(axTrend, [0 trendDisplayMax_s]);

    xlabel(axTrend, 'Lap');
    ylabel(axTrend, 'First-lick latency (s)');
    title(axTrend, sprintf( ...
        '%s: %d-lap rolling median by session', ...
        mouseLabel, ...
        rollingWindow), ...
        'Interpreter', 'none');

    grid(axTrend, 'on');
    box(axTrend, 'on');

    legend(axTrend, ...
        curveHandles(1:curveCount), ...
        curveLabels(1:curveCount), ...
        'Location', 'northeast', ...
        'Interpreter', 'none');
end

end


function validate_mouse_date_pairs( ...
    mouseNames, sessionDates, mouseOrder, dateOrder)

for m = 1:numel(mouseOrder)
    for d = 1:numel(dateOrder)
        pairCount = sum( ...
            strcmp(mouseNames, mouseOrder{m}) & ...
            strcmp(sessionDates, dateOrder{d}));

        if pairCount > 1
            error([ ...
                'Multiple files were selected for mouse %s on %s. ' ...
                'Select only one session per mouse and date.'], ...
                mouseOrder{m}, ...
                dateOrder{d});
        end
    end
end

end


function trendDisplayMax_s = calculate_trend_display_max( ...
    rollingLatencyBySession, cfg)

if isfield(cfg, 'latencyTrendDisplayMax_s') && ...
        ~isempty(cfg.latencyTrendDisplayMax_s)
    trendDisplayMax_s = cfg.latencyTrendDisplayMax_s;

    if ~isscalar(trendDisplayMax_s) || ...
            ~isfinite(trendDisplayMax_s) || ...
            trendDisplayMax_s <= 0
        error( ...
            'cfg.latencyTrendDisplayMax_s must be a positive finite scalar.');
    end

    return
end

if isfield(cfg, 'minimumLatencyTrendDisplayMax_s')
    minimumTrendMax_s = cfg.minimumLatencyTrendDisplayMax_s;
else
    minimumTrendMax_s = 0.5;
end

rollingValues = [];

for s = 1:numel(rollingLatencyBySession)
    values = rollingLatencyBySession{s};
    rollingValues = [ ...
        rollingValues; ...
        values(isfinite(values))]; %#ok<AGROW>
end

if isempty(rollingValues)
    trendDisplayMax_s = min( ...
        cfg.maxLickLatency_s, ...
        minimumTrendMax_s);
else
    paddedTrendMax_s = 1.15 * max(rollingValues);
    roundedTrendMax_s = ceil(10 * paddedTrendMax_s) / 10;

    trendDisplayMax_s = min( ...
        cfg.maxLickLatency_s, ...
        max(minimumTrendMax_s, roundedTrendMax_s));
end

end


function latencyTables = normalize_latency_tables(latencyInput)
if istable(latencyInput)
    latencyTables = {latencyInput};
elseif iscell(latencyInput) && ...
        ~isempty(latencyInput) && ...
        all(cellfun(@istable, latencyInput))
    latencyTables = latencyInput(:)';
else
    error('latencyInput must be a table or a nonempty cell array of tables.');
end
end


function labels = normalize_session_labels( ...
    labelInput, nSessions, fallbackLabel)

if nargin < 1 || isempty(labelInput)
    labels = repmat({fallbackLabel}, nSessions, 1);
elseif ischar(labelInput)
    labels = repmat({labelInput}, nSessions, 1);
elseif isstring(labelInput)
    labels = cellstr(labelInput(:));
elseif iscell(labelInput)
    labels = labelInput(:);
else
    error('Session labels must be text or a cell array of text.');
end

if numel(labels) ~= nSessions
    error('The number of session labels must match the number of tables.');
end

for s = 1:nSessions
    if isstring(labels{s}) && isscalar(labels{s})
        labels{s} = char(labels{s});
    end

    if ~ischar(labels{s})
        error('Every session label must be text.');
    end
end

end


function displayMax_s = calculate_shared_display_max( ...
    latencyTables, cfg)

if isfield(cfg, 'latencyDisplayMax_s') && ...
        ~isempty(cfg.latencyDisplayMax_s)
    displayMax_s = cfg.latencyDisplayMax_s;

    if ~isscalar(displayMax_s) || ...
            ~isfinite(displayMax_s) || ...
            displayMax_s <= 0
        error('cfg.latencyDisplayMax_s must be a positive finite scalar.');
    end

    return
end

if isfield(cfg, 'minimumLatencyDisplayMax_s')
    minimumDisplayMax_s = cfg.minimumLatencyDisplayMax_s;
else
    minimumDisplayMax_s = 0.5;
end

observedLatency = [];

for s = 1:numel(latencyTables)
    T = latencyTables{s};
    observedLatency = [ ...
        observedLatency; ...
        T.LickLatency_s(T.HasFirstLick)]; %#ok<AGROW>
end

if isempty(observedLatency)
    displayMax_s = min( ...
        cfg.maxLickLatency_s, ...
        minimumDisplayMax_s);
else
    paddedObservedMax_s = 1.15 * max(observedLatency);
    roundedObservedMax_s = ceil(10 * paddedObservedMax_s) / 10;

    displayMax_s = min( ...
        cfg.maxLickLatency_s, ...
        max(minimumDisplayMax_s, roundedObservedMax_s));
end

end


function plot_session_raster( ...
    ax, T, mouseName, sessionDate, titleColor, ...
    displayMax_s, maxLap, showYLabel, showLegend)

validReward = T.IsRewardedLap;
validLick = T.HasFirstLick;

hold(ax, 'on');
set(ax, ...
    'Color', [0 0 0], ...
    'YDir', 'reverse', ...
    'Layer', 'top');

lickRows = find(validLick);
for k = 1:numel(lickRows)
    row = lickRows(k);
    plot(ax, ...
        [0 T.LickLatency_s(row)], ...
        [T.Lap(row) T.Lap(row)], ...
        '-', ...
        'Color', [0.55 0.55 0.55], ...
        'LineWidth', 0.7);
end

scatter(ax, ...
    zeros(sum(validReward), 1), ...
    T.Lap(validReward), ...
    28, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [1 0 0]);

scatter(ax, ...
    T.LickLatency_s(validLick), ...
    T.Lap(validLick), ...
    20, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [1 1 1], ...
    'MarkerEdgeColor', [1 1 1]);

xline(ax, 0, ':', ...
    'Color', [1 0.25 0.25], ...
    'LineWidth', 1);

xPadding = 0.03 * displayMax_s;
xlim(ax, [-xPadding displayMax_s]);
ylim(ax, [0.5 maxLap + 0.5]);

xlabel(ax, 'Time from reward (s)');

if showYLabel
    ylabel(ax, 'Lap');
end

title(ax, { ...
    sprintf('%s  %s', mouseName, sessionDate), ...
    sprintf( ...
        '%d rewarded | %d omissions | %d first licks', ...
        sum(T.IsRewardedLap), ...
        sum(T.IsOmissionLap), ...
        sum(T.HasFirstLick))}, ...
    'Interpreter', 'none', ...
    'Color', titleColor);

if showLegend
    hReward = scatter(ax, nan, nan, 28, ...
        'o', 'filled', ...
        'MarkerFaceColor', [1 0 0], ...
        'MarkerEdgeColor', [1 0 0]);
    hLick = scatter(ax, nan, nan, 20, ...
        'o', 'filled', ...
        'MarkerFaceColor', [1 1 1], ...
        'MarkerEdgeColor', [1 1 1]);

    legend(ax, ...
        [hReward hLick], ...
        {'Reward', 'First lick'}, ...
        'Location', 'southeast', ...
        'Color', [0.12 0.12 0.12], ...
        'TextColor', [1 1 1], ...
        'EdgeColor', [0.6 0.6 0.6]);
end

box(ax, 'on');

end
