function fig = plot_lick_latency( ...
    latencyInput, cfg, mouseName, sessionDate)
% PLOT_LICK_LATENCY
% Compares reward-to-first-lick timing across one or more sessions.
%
% Top row:
%   one chronological raster per selected session
%   red dot   = reward delivery at time zero
%   white dot = first post-reward lick
%   gray line = reward-to-lick interval
%
% Bottom row:
%   one shared axis containing a rolling-median latency curve for every
%   selected session.

latencyTables = normalize_latency_tables(latencyInput);
nSessions = numel(latencyTables);

mouseNames = normalize_session_labels( ...
    mouseName, ...
    nSessions, ...
    'UnknownMouse');

sessionDates = normalize_session_labels( ...
    sessionDate, ...
    nSessions, ...
    'UnknownDate');

requiredVariables = { ...
    'Lap', ...
    'RewardCount', ...
    'LickLatency_s', ...
    'IsRewardedLap', ...
    'IsOmissionLap', ...
    'HasMultipleRewards', ...
    'HasFirstLick'};

maxLap = 0;
for s = 1:nSessions
    T = latencyTables{s};

    for k = 1:numel(requiredVariables)
        if ~ismember(requiredVariables{k}, T.Properties.VariableNames)
            error( ...
                'Session %d latency table is missing variable %s.', ...
                s, ...
                requiredVariables{k});
        end
    end

    if isempty(T)
        error('Session %d latency table is empty.', s);
    end

    maxLap = max(maxLap, max(T.Lap));
end

if ~isfield(cfg, 'maxLickLatency_s') || ...
        ~isscalar(cfg.maxLickLatency_s) || ...
        ~isfinite(cfg.maxLickLatency_s) || ...
        cfg.maxLickLatency_s <= 0
    error('A finite positive cfg.maxLickLatency_s is required for plotting.');
end

if ~isfield(cfg, 'latencyRollingWindow_laps')
    cfg.latencyRollingWindow_laps = 10;
end

rollingWindow = max(1, round(cfg.latencyRollingWindow_laps));
displayMax_s = calculate_shared_display_max(latencyTables, cfg);
sessionColors = lines(nSessions);

figWidth = min(0.98, max(0.68, 0.25 * nSessions));

fig = figure( ...
    'Color', 'w', ...
    'Name', 'Multi-session lick latency', ...
    'Units', 'normalized', ...
    'Position', [(1 - figWidth) / 2, 0.08, figWidth, 0.82]);

tl = tiledlayout(fig, 2, nSessions, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

%% Top row: one session raster per chronological dataset
for s = 1:nSessions
    axRaster = nexttile(tl, s);

    plot_session_raster( ...
        axRaster, ...
        latencyTables{s}, ...
        mouseNames{s}, ...
        sessionDates{s}, ...
        sessionColors(s, :), ...
        displayMax_s, ...
        maxLap, ...
        s == 1, ...
        s == nSessions);
end

%% Bottom row: overlaid rolling-median session curves
axTrend = nexttile(tl, nSessions + 1, [1 nSessions]);
hold(axTrend, 'on');

curveHandles = gobjects(nSessions, 1);
curveLabels = cell(nSessions, 1);

for s = 1:nSessions
    T = latencyTables{s};

    rollingLatency = movmedian( ...
        T.LickLatency_s, ...
        rollingWindow, ...
        'omitnan');

    curveHandles(s) = plot(axTrend, ...
        T.Lap, ...
        rollingLatency, ...
        '-', ...
        'Color', sessionColors(s, :), ...
        'LineWidth', 2);

    curveLabels{s} = sprintf( ...
        '%s %s', ...
        mouseNames{s}, ...
        sessionDates{s});
end

xlim(axTrend, [0.5 maxLap + 0.5]);
ylim(axTrend, [0 displayMax_s]);

xlabel(axTrend, 'Lap');
ylabel(axTrend, 'First-lick latency (s)');
title(axTrend, sprintf( ...
    '%d-lap rolling median by session', ...
    rollingWindow));

grid(axTrend, 'on');
box(axTrend, 'on');

legend(axTrend, ...
    curveHandles, ...
    curveLabels, ...
    'Location', 'northeast', ...
    'Interpreter', 'none');

end


function latencyTables = normalize_latency_tables(latencyInput)
if istable(latencyInput)
    latencyTables = {latencyInput};
elseif iscell(latencyInput) && ...
        ~isempty(latencyInput) && ...
        all(cellfun(@istable, latencyInput))
    latencyTables = latencyInput(:)';
else
    error('latencyInput must be a table or a nonempty cell array of tables.');
end
end


function labels = normalize_session_labels( ...
    labelInput, nSessions, fallbackLabel)

if nargin < 1 || isempty(labelInput)
    labels = repmat({fallbackLabel}, nSessions, 1);
elseif ischar(labelInput)
    labels = repmat({labelInput}, nSessions, 1);
elseif isstring(labelInput)
    labels = cellstr(labelInput(:));
elseif iscell(labelInput)
    labels = labelInput(:);
else
    error('Session labels must be text or a cell array of text.');
end

if numel(labels) ~= nSessions
    error('The number of session labels must match the number of tables.');
end

for s = 1:nSessions
    if isstring(labels{s}) && isscalar(labels{s})
        labels{s} = char(labels{s});
    end

    if ~ischar(labels{s})
        error('Every session label must be text.');
    end
end

end


function displayMax_s = calculate_shared_display_max( ...
    latencyTables, cfg)

if isfield(cfg, 'latencyDisplayMax_s') && ...
        ~isempty(cfg.latencyDisplayMax_s)
    displayMax_s = cfg.latencyDisplayMax_s;

    if ~isscalar(displayMax_s) || ...
            ~isfinite(displayMax_s) || ...
            displayMax_s <= 0
        error('cfg.latencyDisplayMax_s must be a positive finite scalar.');
    end

    return
end

if isfield(cfg, 'minimumLatencyDisplayMax_s')
    minimumDisplayMax_s = cfg.minimumLatencyDisplayMax_s;
else
    minimumDisplayMax_s = 0.5;
end

observedLatency = [];

for s = 1:numel(latencyTables)
    T = latencyTables{s};
    observedLatency = [ ...
        observedLatency; ...
        T.LickLatency_s(T.HasFirstLick)]; %#ok<AGROW>
end

if isempty(observedLatency)
    displayMax_s = min( ...
        cfg.maxLickLatency_s, ...
        minimumDisplayMax_s);
else
    paddedObservedMax_s = 1.15 * max(observedLatency);
    roundedObservedMax_s = ceil(10 * paddedObservedMax_s) / 10;

    displayMax_s = min( ...
        cfg.maxLickLatency_s, ...
        max(minimumDisplayMax_s, roundedObservedMax_s));
end

end


function plot_session_raster( ...
    ax, T, mouseName, sessionDate, titleColor, ...
    displayMax_s, maxLap, showYLabel, showLegend)

validReward = T.IsRewardedLap;
validLick = T.HasFirstLick;

hold(ax, 'on');
set(ax, ...
    'Color', [0 0 0], ...
    'YDir', 'reverse', ...
    'Layer', 'top');

lickRows = find(validLick);
for k = 1:numel(lickRows)
    row = lickRows(k);
    plot(ax, ...
        [0 T.LickLatency_s(row)], ...
        [T.Lap(row) T.Lap(row)], ...
        '-', ...
        'Color', [0.55 0.55 0.55], ...
        'LineWidth', 0.7);
end

scatter(ax, ...
    zeros(sum(validReward), 1), ...
    T.Lap(validReward), ...
    28, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [1 0 0], ...
    'MarkerEdgeColor', [1 0 0]);

scatter(ax, ...
    T.LickLatency_s(validLick), ...
    T.Lap(validLick), ...
    20, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [1 1 1], ...
    'MarkerEdgeColor', [1 1 1]);

xline(ax, 0, ':', ...
    'Color', [1 0.25 0.25], ...
    'LineWidth', 1);

xPadding = 0.03 * displayMax_s;
xlim(ax, [-xPadding displayMax_s]);
ylim(ax, [0.5 maxLap + 0.5]);

xlabel(ax, 'Time from reward (s)');

if showYLabel
    ylabel(ax, 'Lap');
end

title(ax, { ...
    sprintf('%s  %s', mouseName, sessionDate), ...
    sprintf( ...
        '%d rewarded | %d omissions | %d first licks', ...
        sum(T.IsRewardedLap), ...
        sum(T.IsOmissionLap), ...
        sum(T.HasFirstLick))}, ...
    'Interpreter', 'none', ...
    'Color', titleColor);

if showLegend
    hReward = scatter(ax, nan, nan, 28, ...
        'o', 'filled', ...
        'MarkerFaceColor', [1 0 0], ...
        'MarkerEdgeColor', [1 0 0]);
    hLick = scatter(ax, nan, nan, 20, ...
        'o', 'filled', ...
        'MarkerFaceColor', [1 1 1], ...
        'MarkerEdgeColor', [1 1 1]);

    legend(ax, ...
        [hReward hLick], ...
        {'Reward', 'First lick'}, ...
        'Location', 'southeast', ...
        'Color', [0.12 0.12 0.12], ...
        'TextColor', [1 1 1], ...
        'EdgeColor', [0.6 0.6 0.6]);
end

box(ax, 'on');

end
