function run_full_pipeline(mousePath, regions, varargin)
% RUN_FULL_PIPELINE
% Thin wrapper that forwards options to the Core driver (select_vr_animal_plots).
% Keeps run_auto_pipeline simple while preserving all the new knobs.

% Defaults (lightweight; most are handled in select_vr_animal_plots)
p = inputParser;
addParameter(p, 'Blocks', {[]});
addParameter(p, 'SmoothingWin', 8);
addParameter(p, 'SavePNGs', false);
addParameter(p, 'PDFName', 'AllUnits_SpatialAnalysis.pdf');
addParameter(p, 'MakeLegacyPlots', true);
addParameter(p, 'ShowTrialIDs', false);
addParameter(p, 'RasterMarkerSize', 2);
addParameter(p, 'SpeedThresh', 2.5);
addParameter(p, 'UseMedianSpeedMask', false);
addParameter(p, 'SaveFIGs', false);
addParameter(p, 'FIGDir', '');
addParameter(p, 'FileNum', NaN);
addParameter(p, 'IsEvenFile', false);
addParameter(p, 'PNGDir', '', @(s)ischar(s)||isstring(s));  % <--- added, ignored
parse(p, varargin{:});
opt = p.Results;

% Call the Core driver directly, pinning AnimalFolder to mousePath
select_vr_animal_plots( ...
    'BaseFolder', fileparts(mousePath), ...
    'AnimalFolder', mousePath, ...
    'Regions', regions, ...
    'Blocks', opt.Blocks, ...
    'SmoothingWin', opt.SmoothingWin, ...
    'SavePNGs', opt.SavePNGs, ...
    'PDFName', opt.PDFName, ...
    'MakeLegacyPlots', opt.MakeLegacyPlots, ...
    'ShowTrialIDs', opt.ShowTrialIDs, ...
    'RasterMarkerSize', opt.RasterMarkerSize, ...
    'SpeedThresh', opt.SpeedThresh, ...
    'UseMedianSpeedMask', opt.UseMedianSpeedMask, ...
    'SaveFIGs', opt.SaveFIGs, ...
    'FIGDir', opt.FIGDir, ...
    'FileNum', opt.FileNum, ...
    'IsEvenFile', opt.IsEvenFile);
end
