function plot_reward_centered_trial_speed( ...
    P, cfg, mouseName, sessionDate, ax)
% PLOT_REWARD_CENTERED_TRIAL_SPEED
% Linear reward-centered lap-by-position speed heatmap.
%
% Lap 1 is at the top. Later laps progress downward.
% Missing speed bins are displayed in black.

axes(ax);
cla(ax);
hold(ax, 'on');

vals = P.speedMat(isfinite(P.speedMat));

if isempty(vals)
    error('No valid speed values after exclusions.');
end

%% Select color limits
if isfield(cfg, 'sharedHeatmapCLim')
    heatmapCLim = cfg.sharedHeatmapCLim;
else
    if cfg.usePercentileColorMax
        cmax = prctile(vals, cfg.colorMaxPercentile);
    else
        cmax = max(vals);
    end

    heatmapCLim = [0 max(cmax, eps)];
end

%% Heatmap
hImg = imagesc( ...
    ax, ...
    P.relativeCenters_deg, ...
    1:P.nTrials, ...
    P.speedMat);

set(hImg, 'AlphaData', isfinite(P.speedMat));

set(ax, ...
    'YDir', 'reverse', ...
    'Color', [0 0 0], ...
    'Layer', 'top', ...
    'FontSize', cfg.axisFontSize);

colormap(ax, parula(256));
caxis(ax, heatmapCLim);

xlim(ax, [-180 180]);
ylim(ax, [0.5 P.nTrials + 0.5]);

%% Current reward center
xline(ax, 0, ':', ...
    'Color', [0.25 0.25 0.25], ...
    'LineWidth', 1.2);

%% Old reward location for shifted later sessions
add_old_reward_location_line(ax, P, true);

%% Rewarded-trial licks: white
if ~isempty(P.lickX_deg)
    scatter(ax, ...
        P.lickX_deg, ...
        P.lickLap, ...
        max(cfg.lickDotSize, 1)^2, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor', [1 1 1], ...
        'MarkerEdgeColor', [1 1 1]);
end

%% Reward-omission-trial licks: pink
if ~isempty(P.omissionLickX_deg)
    scatter(ax, ...
        P.omissionLickX_deg, ...
        P.omissionLickLap, ...
        max(cfg.omissionLickDotSize, 1)^2, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor', [1.0 0.4 0.75], ...
        'MarkerEdgeColor', [1.0 0.4 0.75]);
end

%% Reward deliveries: red
if ~isempty(P.rewardX_deg)
    scatter(ax, ...
        P.rewardX_deg, ...
        P.rewardLap, ...
        max(cfg.rewardDotSize, 1)^2, ...
        '.', ...
        'MarkerEdgeColor', [1 0 0]);
end

%% Labels
ylabel(ax, 'Lap');

title(ax, sprintf('%s  %s', mouseName, sessionDate), ...
    'Interpreter', 'none', ...
    'FontSize', cfg.titleFontSize);

set(ax, ...
    'XTick', [-180 -90 0 90 180], ...
    'XTickLabel', []);

cb = colorbar(ax);
ylabel(cb, 'Speed cm/s');

box(ax, 'on');

end
